seeds:
  - name: lkp_divisions
    config:
      schema: "{{env_var('DBT_LOOKUP_SCHEMA', 'LOOKUP_DEV')}}"
  - name: lkp_categories
    config:
      schema: "{{env_var('DBT_LOOKUP_SCHEMA', 'LOOKUP_DEV')}}"
  - name: lkp_shippers
    config:
      schema: "{{env_var('DBT_LOOKUP_SCHEMA', 'LOOKUP_DEV')}}"
